server:
  port: 8083

spring:
  application:
    name: order-service
  datasource:
    url: jdbc:mysql://localhost:3309/order_db
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    defer-datasource-initialization: true
  sql:
    init:
      mode: always

# Shipper Service URL for inter-service communication
shipper-service:
  url: http://localhost:8084
